#!/usr/bin/env python3
"""
Regenerates assets/game/js/manifest.js from whatever image files are
sitting in assets/game/headshots/.

Run from anywhere; it locates itself via this file's path, so:
    python3 assets/game/generate-manifest.py
works from the project root.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
HEADSHOTS_DIR = os.path.join(HERE, 'headshots')
OUT_PATH = os.path.join(HERE, 'js', 'manifest.js')
VALID_EXT = ('.png', '.webp', '.jpg', '.jpeg')

def main():
    files = sorted(
        f for f in os.listdir(HEADSHOTS_DIR)
        if f.lower().endswith(VALID_EXT)
    )
    if not files:
        print('No images found in', HEADSHOTS_DIR)
        return

    lines = [
        '/**',
        ' * GAME MANIFEST — auto-generated by generate-manifest.py',
        ' * Do not hand-edit unless you also plan to keep this in sync manually.',
        ' */',
        'window.GAME_MANIFEST = [',
    ]
    lines += [f"  '{f}'," for f in files]
    lines += ['];', '']

    with open(OUT_PATH, 'w') as fh:
        fh.write('\n'.join(lines))

    print(f'Wrote {len(files)} entries to {OUT_PATH}')

if __name__ == '__main__':
    main()
